name: CI

on: [push]

jobs:
  job_1:
    name: Python Crawler
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1 
    - name: Install Dependence
      run: pip install requests-html
    - name: Run pa.py
      run: python pa.py
    - name: list
      run: ls
      
    - name: Failure test
      if: failure()
      run: echo 55555  
      
  job_2:
    name: Nodejs md2html
    needs: [job_1]
    runs-on: ubuntu-latest
    
    steps:
    - name: list
      run: ls
      
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      
    - name: Install Dependence
      run: npm install fs marked
      
    - name: Markdown to HTML
      run: node md2html.js
    
    - name: Failure test
      if: failure()
      run: echo 55555  
    
  job_3:    
    name: Ppdate repo
    needs: [job_2]
    runs-on: ubuntu-latest    
    
    steps:
    - name: list
      run: ls
    
    - name: Upload to this repo
      run: |
        git config --global user.name "growvv"
        git config --global user.email "2092876368@qq.com"
        git add index.html
        git commit -m 'upload pa result'
        git push -u origin master && echo ok
        
    - name: Failure test
      if: failure()
      run: echo 55555  
