name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Download a pic
      run: wget https://pan.rogn.top/Image/1.png
    
    - name: Upload this repo
      run: |
        git add 1.png
        git commit -m 'upload pa result'
        git push -u origin master && echo 333
